### ISSUE TITLE
No working anymore

### ISSUE THREAD

**Issue by Iotnet** [nicolsc/sigfox-message-location#2]
Hello the library is not working anymore, maybe is the change of API in the SIGFOX Backend. 

message-localisation:sigfox API Call — https://backend.sigfox.com/api/devices/XXXXXX/messages +0ms
  message-localisation:app Err  ?undefined +347ms
  message-localisation:app /messages routes +21s
  message-localisation:app deviceid	:	XXXXX +0ms
  message-localisation:app extension	:	undefined +0ms
  message-localisation:app */* +0ms

There is no problem with the rights for this device.

Thanks for your help. 

Regards 

Daniel

**Comment by nicolsc** [comment]
Hi Daniel

You're right, this API isn't available anymore.
I'll try to port this to the API v2, which has its own limitations (message history up to 3 days only)

**Comment by Iotnet** [comment]
i clone the git  for the changes , but now i have an error when i start npm :

Error: Cannot find module 'debug'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/dguevara/sigfox/sigfox-message-location/server.js:4:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

**Comment by Iotnet** [comment]
Did an npm install and all is working now. 

Tahnks
